## Import libraries

In [1]:
import pandas as pd
import numpy as np

# to be able to display all columns and all rows of the dataframe 
#   (now that we know this one is small, only 700 rows)
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [2]:
data_preprocessed = pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_preprocessed.csv')
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,None,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,0,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,1,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,0,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,0,7,3,289,36,33,239.554,30,0,2,1,2

## Logistic Regression
We will classify all rows into two classes:
 - excessively absent - those with absenteeism over the median
 - average absent - those with absenteeism equal or under the median.

In [3]:
#Calculate the median
data_preprocessed['Absenteeism Time in Hours'].median()

np.float64(3.0)

## Create the targets for machine learning
3 hours is the cut line.
Let's create the targets array with a value o 1 for those rows having absenteeism over 3.

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,None,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,0,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,1,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,0,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,0,7,3,289,36,33,239.554,30,0,2,1,2,0

### Verify that the targets are evenly distributed.
For a logistic regression up to 60-40 division is sufficiently even.

In [6]:
targets.sum()/targets.shape[0]

np.float64(0.45571428571428574)

Make a checkpoint "data_with_targets"

In [7]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)
data_with_targets.head()

,Reason_1,Reason_2,Reason_3,Reason_4,None,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,0,7,1,289,36,33,239.554,30,0,2,1,1
1,0,0,0,0,1,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,0,7,2,179,51,38,239.554,31,0,0,0,0
3,1,0,0,0,0,7,3,279,5,39,239.554,24,0,2,0,1
4,0,0,0,1,0,7,3,289,36,33,239.554,30,0,2,1,0

In [8]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs.head()

,Reason_1,Reason_2,Reason_3,Reason_4,None,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,0,0,0,1,0,7,1,289,36,33,239.554,30,0,2,1
1,0,0,0,0,1,7,1,118,13,50,239.554,31,0,1,0
2,0,0,0,1,0,7,2,179,51,38,239.554,31,0,0,0
3,1,0,0,0,0,7,3,279,5,39,239.554,24,0,2,0
4,0,0,0,1,0,7,3,289,36,33,239.554,30,0,2,1

## Standardize data

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

In [11]:
class CustomScaler(BaseEstimator,TransformerMixin):
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self,x,y=None):
        self.scaler.fit(x[self.columns],y)
        self.mean_ = np.mean(x[self.columns])
        self.var_ = np.var(x[self.columns])
        return self

    def transform(self,x,y=None,copy=None):
        init_col_order=x.columns
        x_scaled = pd.DataFrame(self.scaler.transform(x[self.columns]),columns=self.columns)
        x_not_scaled = x.loc[:,~x.columns.isin(self.columns)]
        return pd.concat([x_not_scaled,x_scaled],axis=1)[init_col_order]

In [12]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'None', 'Month',
       'DayOfWeek', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [13]:
columns_to_scale = ['Month','DayOfWeek', 'Transportation Expense', 'Distance to Work', 'Age',
                    'Daily Work Load Average', 'Body Mass Index','Children', 'Pets']

In [14]:
#absenteeism_scaler = StandardScaler()
absenteeism_scaler = CustomScaler(columns_to_scale)
absenteeism_scaler.fit(unscaled_inputs)

TypeError: StandardScaler.__init__() takes 1 positional argument but 4 were given

In [13]:
scaled_inputs = absenteeisrm_scaler.transform(unscaled_inputs)

In [14]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [15]:
scaled_inputs.shape

(700, 15)

## Split and shuffle data

In [16]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8,shuffle=True, random_state=20)

In [24]:
print(x_train.shape, y_train.shape)

(560, 15) (560,)

In [25]:
print(x_test.shape, y_test.shape)

(140, 15) (140,)

## Logistic regression with SkLearn

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [27]:
reg = LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression()

In [28]:
reg.score(x_train, y_train)

0.7857142857142857

## Manually check the accuracy

In [29]:
# make the model classify the inputs and store the classification vector
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [30]:
#Compare clasiffication vector with the targets
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

In [31]:
# To view how many True we got (how many did the model classify correctly)
#      - count the correctly classified (those equal to the targets, those True in the comparison)
np.sum(model_outputs==y_train)

np.int64(440)

In [32]:
#      - count how many elements were classified
model_outputs.shape[0]

560

In [33]:
#      - Divide the correct by the total
np.sum(model_outputs==y_train)/model_outputs.shape[0]

np.float64(0.7857142857142857)

### Find intercept and coeficients

In [34]:
intercept = reg.intercept_
coeficients = reg.coef_
feature_name = unscaled_inputs.columns.values

In [39]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(coeficients)
summary_table

               Feature name  Coefficient
0                  Reason_1     0.624318
1                  Reason_2     0.025250
2                  Reason_3     0.611953
3                  Reason_4    -0.331296
4                      None    -1.259171
5                     Month     0.193879
6                 DayOfWeek    -0.072987
7    Transportation Expense     0.740016
8          Distance to Work    -0.054389
9                       Age    -0.214266
10  Daily Work Load Average    -0.006456
11          Body Mass Index     0.334504
12                Education    -0.146205
13                 Children     0.397704
14                     Pets    -0.352588

In [40]:
# Add the intercept at the beginning
summary_table.index = summary_table.index+1
summary_table.loc[0] = 'Intercept', reg.intercept_[0]
summary_table = summary_table.sort_index()
summary_table

               Feature name  Coefficient
1                  Reason_1     0.624318
2                  Reason_2     0.025250
3                  Reason_3     0.611953
4                  Reason_4    -0.331296
5                      None    -1.259171
6                     Month     0.193879
7                 DayOfWeek    -0.072987
8    Transportation Expense     0.740016
9          Distance to Work    -0.054389
10                      Age    -0.214266
11  Daily Work Load Average    -0.006456
12          Body Mass Index     0.334504
13                Education    -0.146205
14                 Children     0.397704
15                     Pets    -0.352588
0                 Intercept    -0.316836

In [42]:
summary_table['Odds_ratio']= np.exp(summary_table.Coefficient)
summary_table

               Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.316836    0.728450
1                  Reason_1     0.624318    1.866972
2                  Reason_2     0.025250    1.025572
3                  Reason_3     0.611953    1.844029
4                  Reason_4    -0.331296    0.717993
5                      None    -1.259171    0.283889
6                     Month     0.193879    1.213950
7                 DayOfWeek    -0.072987    0.929613
8    Transportation Expense     0.740016    2.095969
9          Distance to Work    -0.054389    0.947063
10                      Age    -0.214266    0.807133
11  Daily Work Load Average    -0.006456    0.993565
12          Body Mass Index     0.334504    1.397248
13                Education    -0.146205    0.863981
14                 Children     0.397704    1.488404
15                     Pets    -0.352588    0.702866

In [45]:
summary_table.sort_values('Feature name', ascending=False)

               Feature name  Coefficient  Odds_ratio
8    Transportation Expense     0.740016    2.095969
4                  Reason_4    -0.331296    0.717993
3                  Reason_3     0.611953    1.844029
2                  Reason_2     0.025250    1.025572
1                  Reason_1     0.624318    1.866972
15                     Pets    -0.352588    0.702866
5                      None    -1.259171    0.283889
6                     Month     0.193879    1.213950
0                 Intercept    -0.316836    0.728450
13                Education    -0.146205    0.863981
9          Distance to Work    -0.054389    0.947063
7                 DayOfWeek    -0.072987    0.929613
11  Daily Work Load Average    -0.006456    0.993565
14                 Children     0.397704    1.488404
12          Body Mass Index     0.334504    1.397248
10                      Age    -0.214266    0.807133