In [1]:
import pandas as pd

In [2]:
#Load data from .CSV: drop headers and 1st column (the ID).
raw_csv_data = pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_data.csv', sep=',', header=0, index_col='ID',
                          dtype = {'ID': int,'Reason for Absence':int,'Transportation Expense':int,
                                    'Distance to Work':int,'Age':int,'Daily Work Load Average':float,'Body Mass Index':int,
                                    'Education':int,'Children':int,'Pets':int,'Absenteeism Time in Hours':int},
                           parse_dates=['Date'], date_format="%d/%m/%Y", decimal='.'
)
raw_csv_data.info

<bound method DataFrame.info of     Reason for Absence       Date  Transportation Expense  Distance to Work  \
ID
11                  26 2015-07-07                     289                36
36                   0 2015-07-14                     118                13
3                   23 2015-07-15                     179                51
7                    7 2015-07-16                     279                 5
11                  23 2015-07-23                     289                36
..                 ...        ...                     ...               ...
17                  10 2018-05-23                     179                22
28                   6 2018-05-23                     225                26
18                  10 2018-05-24                     330                16
25                  23 2018-05-24                     235                16
15                  28 2018-05-31                     291                31

    Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
ID
11   33                  239.554               30          1         2     1
36   50                  239.554               31          1         1     0
3    38                  239.554               31          1         0     0
7    39                  239.554               24          1         2     0
11   33                  239.554               30          1         2     1
..  ...                      ...              ...        ...       ...   ...
17   40                  237.656               22          2         2     0
28   28                  237.656               24          1         1     2
18   28                  237.656               25          2         0     0
25   32                  237.656               25          3         0     0
15   40                  237.656               25          1         1     1

    Absenteeism Time in Hours
ID
11                          4
36                          0
3                           2
7                           4
11                          2
..                        ...
17                          8
28                          3
18                          8
25                          2
15                          2

[700 rows x 11 columns]>

In [3]:
raw_csv_data.describe()

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
count,700.000000,700,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
mean,19.411429,2016-12-31 00:45:15.428571392,222.347143,29.892857,36.417143,271.801774,26.737143,1.282857,1.021429,0.687143,6.761429
min,0.000000,2015-07-06 00:00:00,118.000000,5.000000,27.000000,205.917000,19.000000,1.000000,0.000000,0.000000,0.000000
25%,13.000000,2016-03-27 06:00:00,179.000000,16.000000,31.000000,241.476000,24.000000,1.000000,0.000000,0.000000,2.000000
50%,23.000000,2016-12-19 00:00:00,225.000000,26.000000,37.000000,264.249000,25.000000,1.000000,1.000000,0.000000,3.000000
75%,27.000000,2017-10-26 06:00:00,260.000000,50.000000,40.000000,294.217000,31.000000,1.000000,2.000000,1.000000,8.000000
max,28.000000,2018-05-31 00:00:00,388.000000,52.000000,58.000000,378.884000,38.000000,4.000000,4.000000,8.000000,120.000000
std,8.356292,NaN,66.312960,14.804446,6.379083,40.021804,4.254701,0.668090,1.112215,1.166095,12.670082

In [9]:
absence_groups = pd.DataFrame(raw_csv_data['Reason for Absence'].isin(range(1,15)).map({True:1,False:0}))
absence_groups['Reason_2'] = raw_csv_data['Reason for Absence'].isin(range(15,18)).map({True:1,False:0})
absence_groups['Reason_3'] = raw_csv_data['Reason for Absence'].isin(range(18,22)).map({True:1,False:0})
absence_groups['Reason_4'] = raw_csv_data['Reason for Absence'].isin(range(22,29)).map({True:1,False:0})
absence_groups['NoReason'] = (raw_csv_data['Reason for Absence'] == 0).map({True:1,False:0})
absence_groups

    Reason for Absence  Reason_2  Reason_3  Reason_4  NoReason
ID
11                   0         0         0         1         0
36                   0         0         0         0         1
3                    0         0         0         1         0
7                    1         0         0         0         0
11                   0         0         0         1         0
..                 ...       ...       ...       ...       ...
17                   1         0         0         0         0
28                   1         0         0         0         0
18                   1         0         0         0         0
25                   0         0         0         1         0
15                   0         0         0         1         0

[700 rows x 5 columns]

### Rename
- Get the column names
- Store the array in a variable
- Edit names in place
- Set objects columns to the renamed ones

In [11]:
absence_groups.columns.values

array(['Reason for Absence', 'Reason_2', 'Reason_3', 'Reason_4',
       'NoReason'], dtype=object)

In [12]:
absence_columns = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'NoReason']
absence_groups.columns = absence_columns
absence_groups.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'NoReason'],
      dtype=object)

### Reorder
- Get the column names
- Store the array in a variable
- Re-order the column names without changing the names
- Make the object equal to the object "of" the reordered column names

In [13]:
absence_columns = ['NoReason', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']
absence_groups = absence_groups[absence_columns]
absence_groups

    NoReason  Reason_1  Reason_2  Reason_3  Reason_4
ID
11         0         0         0         0         1
36         1         0         0         0         0
3          0         0         0         0         1
7          0         1         0         0         0
11         0         0         0         0         1
..       ...       ...       ...       ...       ...
17         0         1         0         0         0
28         0         1         0         0         0
18         0         1         0         0         0
25         0         0         0         0         1
15         0         0         0         0         1

[700 rows x 5 columns]

## Check 'Reason for Absence'

In [15]:
raw_csv_data['Reason for Absence']

ID
11    26
36     0
3     23
7      7
11    23
      ..
17    10
28     6
18    10
25    23
15    28
Name: Reason for Absence, Length: 700, dtype: int64

In [16]:
# There are 28 different values
pd.unique(raw_csv_data['Reason for Absence']).shape

(28,)

In [17]:
#  . . . that start at 0
pd.unique(raw_csv_data['Reason for Absence']).min()

np.int64(0)

In [18]:
#  . . . and up to 28, so one of the values is missing
pd.unique(raw_csv_data['Reason for Absence']).max()

np.int64(28)

In [19]:
# Dummies: we get a dummy column for each present value. No column for the absent '20'
reason_columns = pd.get_dummies(raw_csv_data['Reason for Absence'], dtype=int)
reason_columns

,0,1,2,3,4,5,6,7,8,9,...,18,19,21,22,23,24,25,26,27,28
ID,,,,,,,,,,,,,,,,,,,,,
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
36,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

Let's verify that the dummies are correct: there is one and only one dummy column with value 1 for each row.

In [28]:
reason_columns['check'] = reason_columns.sum(axis=1)
reason_columns['check'].unique()

array([1])

In [29]:
#there are 700 '1' in total in the column "check"
reason_columns['check'].sum(axis=0)

np.int64(700)

In [30]:
reason_columns=reason_columns.drop(['check'], axis=1)

The process is sound. Do it again but dropping the first one.

In [55]:
reason_columns = pd.get_dummies(raw_csv_data['Reason for Absence'], dtype=int, drop_first = True)

In [56]:
reason_columns

,1,2,3,4,5,6,7,8,9,10,...,18,19,21,22,23,24,25,26,27,28
ID,,,,,,,,,,,,,,,,,,,,,
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [57]:
reason_type_1 = reason_columns.loc[:,1:14].max(axis=1)
reason_type_2 = reason_columns.loc[:,15:17].max(axis=1)
reason_type_3 = reason_columns.loc[:,18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:,22:].max(axis=1)

In [58]:
reason_type_1

ID
11    0
36    0
3     0
7     1
11    0
     ..
17    1
28    1
18    1
25    0
15    0
Length: 700, dtype: int64

In [59]:
reason_type_2

ID
11    0
36    0
3     0
7     0
11    0
     ..
17    0
28    0
18    0
25    0
15    0
Length: 700, dtype: int64

In [60]:
reason_type_3

ID
11    0
36    0
3     0
7     0
11    0
     ..
17    0
28    0
18    0
25    0
15    0
Length: 700, dtype: int64

In [61]:
reason_type_4

ID
11    1
36    0
3     1
7     0
11    1
     ..
17    0
28    0
18    0
25    1
15    1
Length: 700, dtype: int64

In [64]:
reasons = pd.DataFrame(reason_type_1)

In [65]:
reasons

    0
ID
11  0
36  0
3   0
7   1
11  0
.. ..
17  1
28  1
18  1
25  0
15  0

[700 rows x 1 columns]

In [66]:
reasons = pd.concat([reasons, reason_type_2,reason_type_3,reason_type_4],axis=1)

In [67]:
reasons.columns.values

array([0, 0, 1, 2])

In [68]:
reasons.columns = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']
reasons

    Reason_1  Reason_2  Reason_3  Reason_4
ID
11         0         0         0         1
36         0         0         0         0
3          0         0         0         1
7          1         0         0         0
11         0         0         0         1
..       ...       ...       ...       ...
17         1         0         0         0
28         1         0         0         0
18         1         0         0         0
25         0         0         0         1
15         0         0         0         1

[700 rows x 4 columns]

## Compare both paths
Now we have the path from the lecture ready. Compare the result with my path in variable absence_groups

In [69]:
absence_groups

    NoReason  Reason_1  Reason_2  Reason_3  Reason_4
ID
11         0         0         0         0         1
36         1         0         0         0         0
3          0         0         0         0         1
7          0         1         0         0         0
11         0         0         0         0         1
..       ...       ...       ...       ...       ...
17         0         1         0         0         0
28         0         1         0         0         0
18         0         1         0         0         0
25         0         0         0         0         1
15         0         0         0         0         1

[700 rows x 5 columns]

In [73]:
reasons.info()

<class 'pandas.core.frame.DataFrame'>
Index: 700 entries, 11 to 15
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Reason_1  700 non-null    int64
 1   Reason_2  700 non-null    int64
 2   Reason_3  700 non-null    int64
 3   Reason_4  700 non-null    int64
dtypes: int64(4)
memory usage: 43.5 KB

In [74]:
absence_groups.info()

<class 'pandas.core.frame.DataFrame'>
Index: 700 entries, 11 to 15
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NoReason  700 non-null    int64
 1   Reason_1  700 non-null    int64
 2   Reason_2  700 non-null    int64
 3   Reason_3  700 non-null    int64
 4   Reason_4  700 non-null    int64
dtypes: int64(5)
memory usage: 49.0 KB

In [75]:
absence_groups_4 = absence_groups.copy()

In [76]:
absence_groups_4 = absence_groups_4.drop(['NoReason'], axis=1)
absence_groups_4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 700 entries, 11 to 15
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Reason_1  700 non-null    int64
 1   Reason_2  700 non-null    int64
 2   Reason_3  700 non-null    int64
 3   Reason_4  700 non-null    int64
dtypes: int64(4)
memory usage: 43.5 KB

In [77]:
compared = reasons==absence_groups_4
compared.info()

<class 'pandas.core.frame.DataFrame'>
Index: 700 entries, 11 to 15
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Reason_1  700 non-null    bool
 1   Reason_2  700 non-null    bool
 2   Reason_3  700 non-null    bool
 3   Reason_4  700 non-null    bool
dtypes: bool(4)
memory usage: 24.4 KB

In [78]:
compared

    Reason_1  Reason_2  Reason_3  Reason_4
ID
11      True      True      True      True
36      True      True      True      True
3       True      True      True      True
7       True      True      True      True
11      True      True      True      True
..       ...       ...       ...       ...
17      True      True      True      True
28      True      True      True      True
18      True      True      True      True
25      True      True      True      True
15      True      True      True      True

[700 rows x 4 columns]

In [85]:
compared.sum(axis=0)
# they are all true, they are all equal: 700x4 True values

Reason_1    700
Reason_2    700
Reason_3    700
Reason_4    700
dtype: int64

In [87]:
unscaled_data=raw_csv_data.copy()
unscaled_data

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
ID,,,,,,,,,,,
11,26,2015-07-07,289,36,33,239.554,30,1,2,1,4
36,0,2015-07-14,118,13,50,239.554,31,1,1,0,0
3,23,2015-07-15,179,51,38,239.554,31,1,0,0,2
7,7,2015-07-16,279,5,39,239.554,24,1,2,0,4
11,23,2015-07-23,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...
17,10,2018-05-23,179,22,40,237.656,22,2,2,0,8
28,6,2018-05-23,225,26,28,237.656,24,1,1,2,3
18,10,2018-05-24,330,16,28,237.656,25,2,0,0,8
25,23,2018-05-24,235,16,32,237.656,25,3,0,0,2
15,28,2018-05-31,291,31,40,237.656,25,1,1,1,2

In [88]:
unscaled_data.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [89]:
unscaled_data = unscaled_data.drop(['Reason for Absence', 'Date', 'Education'], axis=1)
unscaled_data.columns.values

array(['Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [90]:
unscaled_data['Month']=raw_csv_data['Date'].dt.month
unscaled_data['DayOfWeek']=raw_csv_data['Date'].dt.dayofweek
unscaled_data.head()

,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Children,Pets,Absenteeism Time in Hours,Month,DayOfWeek
ID,,,,,,,,,,
11,289,36,33,239.554,30,2,1,4,7,1
36,118,13,50,239.554,31,1,0,0,7,1
3,179,51,38,239.554,31,0,0,2,7,2
7,279,5,39,239.554,24,2,0,4,7,3
11,289,36,33,239.554,30,2,1,2,7,3

In [92]:
unscaled_data['Education'] = raw_csv_data['Education'].isin(range(2,5)).map({True:1,False:0})
unscaled_data.head()

,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Children,Pets,Absenteeism Time in Hours,Month,DayOfWeek,EducationLevel
ID,,,,,,,,,,,
11,289,36,33,239.554,30,2,1,4,7,1,0
36,118,13,50,239.554,31,1,0,0,7,1,0
3,179,51,38,239.554,31,0,0,2,7,2,0
7,279,5,39,239.554,24,2,0,4,7,3,0
11,289,36,33,239.554,30,2,1,2,7,3,0

In [96]:
unscaled_data['Education'].unique()

array([0, 1])

In [97]:
unscaled_data['Education'].value_counts()

Education
0    583
1    117
Name: count, dtype: int64

In [98]:
unscaled_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 700 entries, 11 to 15
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Transportation Expense     700 non-null    int64
 1   Distance to Work           700 non-null    int64
 2   Age                        700 non-null    int64
 3   Daily Work Load Average    700 non-null    float64
 4   Body Mass Index            700 non-null    int64
 5   Children                   700 non-null    int64
 6   Pets                       700 non-null    int64
 7   Absenteeism Time in Hours  700 non-null    int64
 8   Month                      700 non-null    int32
 9   DayOfWeek                  700 non-null    int32
 10  Education                  700 non-null    int64
dtypes: float64(1), int32(2), int64(8)
memory usage: 76.3 KB

In [102]:
absenteeism_preprocessed = pd.concat([unscaled_data,absence_groups.iloc[:,1:]],axis=1)
absenteeism_preprocessed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 700 entries, 11 to 15
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Transportation Expense     700 non-null    int64
 1   Distance to Work           700 non-null    int64
 2   Age                        700 non-null    int64
 3   Daily Work Load Average    700 non-null    float64
 4   Body Mass Index            700 non-null    int64
 5   Children                   700 non-null    int64
 6   Pets                       700 non-null    int64
 7   Absenteeism Time in Hours  700 non-null    int64
 8   Month                      700 non-null    int32
 9   DayOfWeek                  700 non-null    int32
 10  Education                  700 non-null    int64
 11  Reason_1                   700 non-null    int64
 12  Reason_2                   700 non-null    int64
 13  Reason_3                   700 non-null    int64
 14  Reason_4                   700 non-null    int64
dtypes: float64(1), int32(2), int64(12)
memory usage: 98.2 KB

In [103]:
absenteeism_preprocessed.columns.values

array(['Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets',
       'Absenteeism Time in Hours', 'Month', 'DayOfWeek', 'Education',
       'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4'], dtype=object)

In [105]:
absenteeism_preprocessed = absenteeism_preprocessed[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
                                                    'DayOfWeek', 'Transportation Expense', 'Distance to Work',
                                                    'Age', 'Daily Work Load Average', 'Body Mass Index',
                                                    'Education', 'Children', 'Pets', 'Absenteeism Time in Hours']]

In [106]:
absenteeism_preprocessed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 700 entries, 11 to 15
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Reason_1                   700 non-null    int64
 1   Reason_2                   700 non-null    int64
 2   Reason_3                   700 non-null    int64
 3   Reason_4                   700 non-null    int64
 4   Month                      700 non-null    int32
 5   DayOfWeek                  700 non-null    int32
 6   Transportation Expense     700 non-null    int64
 7   Distance to Work           700 non-null    int64
 8   Age                        700 non-null    int64
 9   Daily Work Load Average    700 non-null    float64
 10  Body Mass Index            700 non-null    int64
 11  Education                  700 non-null    int64
 12  Children                   700 non-null    int64
 13  Pets                       700 non-null    int64
 14  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int32(2), int64(12)
memory usage: 98.2 KB

In [107]:
absenteeism_preprocessed.to_csv('../../../../statistics/python/Absenteeism/Absenteeism_preprocessed_second.csv', index=False)