In [1]:
import pandas as pd

In [2]:
#Load data from .CSV: drop headers and 1st column (the ID).
raw_csv_data = pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_data.csv', sep=',', header=0,
                          dtype = {'ID': int,'Reason for Absence':int,'Transportation Expense':int,
                                    'Distance to Work':int,'Age':int,'Daily Work Load Average':float,'Body Mass Index':int,
                                    'Education':int,'Children':int,'Pets':int,'Absenteeism Time in Hours':int},
                           parse_dates=['Date'], date_format="%d/%m/%Y", decimal='.'
)
raw_csv_data.info

<bound method DataFrame.info of      ID  Reason for Absence       Date  Transportation Expense  \
0    11                  26 2015-07-07                     289
1    36                   0 2015-07-14                     118
2     3                  23 2015-07-15                     179
3     7                   7 2015-07-16                     279
4    11                  23 2015-07-23                     289
..   ..                 ...        ...                     ...
695  17                  10 2018-05-23                     179
696  28                   6 2018-05-23                     225
697  18                  10 2018-05-24                     330
698  25                  23 2018-05-24                     235
699  15                  28 2018-05-31                     291

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30
1                  13   50                  239.554               31
2                  51   38                  239.554               31
3                   5   39                  239.554               24
4                  36   33                  239.554               30
..                ...  ...                      ...              ...
695                22   40                  237.656               22
696                26   28                  237.656               24
697                16   28                  237.656               25
698                16   32                  237.656               25
699                31   40                  237.656               25

     Education  Children  Pets  Absenteeism Time in Hours
0            1         2     1                          4
1            1         1     0                          0
2            1         0     0                          2
3            1         2     0                          4
4            1         2     1                          2
..         ...       ...   ...                        ...
695          2         2     0                          8
696          1         1     2                          3
697          2         0     0                          8
698          3         0     0                          2
699          1         1     1                          2

[700 rows x 12 columns]>

In [3]:
raw_csv_data = raw_csv_data.drop(['ID'], axis=1)

In [4]:
raw_csv_data.describe()

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
count,700.000000,700,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
mean,19.411429,2016-12-31 00:45:15.428571392,222.347143,29.892857,36.417143,271.801774,26.737143,1.282857,1.021429,0.687143,6.761429
min,0.000000,2015-07-06 00:00:00,118.000000,5.000000,27.000000,205.917000,19.000000,1.000000,0.000000,0.000000,0.000000
25%,13.000000,2016-03-27 06:00:00,179.000000,16.000000,31.000000,241.476000,24.000000,1.000000,0.000000,0.000000,2.000000
50%,23.000000,2016-12-19 00:00:00,225.000000,26.000000,37.000000,264.249000,25.000000,1.000000,1.000000,0.000000,3.000000
75%,27.000000,2017-10-26 06:00:00,260.000000,50.000000,40.000000,294.217000,31.000000,1.000000,2.000000,1.000000,8.000000
max,28.000000,2018-05-31 00:00:00,388.000000,52.000000,58.000000,378.884000,38.000000,4.000000,4.000000,8.000000,120.000000
std,8.356292,NaN,66.312960,14.804446,6.379083,40.021804,4.254701,0.668090,1.112215,1.166095,12.670082

In [5]:
raw_csv_data['Reason_1'] = raw_csv_data['Reason for Absence'].isin(range(1,15)).map({True:1,False:0})
raw_csv_data['Reason_2'] = raw_csv_data['Reason for Absence'].isin(range(15,18)).map({True:1,False:0})
raw_csv_data['Reason_3'] = raw_csv_data['Reason for Absence'].isin(range(18,22)).map({True:1,False:0})
raw_csv_data['Reason_4'] = raw_csv_data['Reason for Absence'].isin(range(22,29)).map({True:1,False:0})
raw_csv_data['None'] = (raw_csv_data['Reason for Absence'] == 0).map({True:1,False:0})

In [6]:
raw_csv_data['Reason for Absence']

0      26
1       0
2      23
3       7
4      23
       ..
695    10
696     6
697    10
698    23
699    28
Name: Reason for Absence, Length: 700, dtype: int64

In [7]:
pd.unique(raw_csv_data['Reason for Absence']).shape

(28,)

In [8]:
pd.unique(raw_csv_data['Reason for Absence']).min()

np.int64(0)

In [9]:
pd.unique(raw_csv_data['Reason for Absence']).max()

np.int64(28)

In [10]:
reason_columns = pd.get_dummies(raw_csv_data['Reason for Absence'], dtype=int)
reason_columns

,0,1,2,3,4,5,6,7,8,9,...,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
696,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [11]:
raw_csv_data.info

<bound method DataFrame.info of      Reason for Absence       Date  Transportation Expense  Distance to Work  \
0                    26 2015-07-07                     289                36
1                     0 2015-07-14                     118                13
2                    23 2015-07-15                     179                51
3                     7 2015-07-16                     279                 5
4                    23 2015-07-23                     289                36
..                  ...        ...                     ...               ...
695                  10 2018-05-23                     179                22
696                   6 2018-05-23                     225                26
697                  10 2018-05-24                     330                16
698                  23 2018-05-24                     235                16
699                  28 2018-05-31                     291                31

     Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0     33                  239.554               30          1         2     1
1     50                  239.554               31          1         1     0
2     38                  239.554               31          1         0     0
3     39                  239.554               24          1         2     0
4     33                  239.554               30          1         2     1
..   ...                      ...              ...        ...       ...   ...
695   40                  237.656               22          2         2     0
696   28                  237.656               24          1         1     2
697   28                  237.656               25          2         0     0
698   32                  237.656               25          3         0     0
699   40                  237.656               25          1         1     1

     Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  None
0                            4         0         0         0         1     0
1                            0         0         0         0         0     1
2                            2         0         0         0         1     0
3                            4         1         0         0         0     0
4                            2         0         0         0         1     0
..                         ...       ...       ...       ...       ...   ...
695                          8         1         0         0         0     0
696                          3         1         0         0         0     0
697                          8         1         0         0         0     0
698                          2         0         0         0         1     0
699                          2         0         0         0         1     0

[700 rows x 16 columns]>

In [12]:
raw_csv_data.dtypes

Reason for Absence                    int64
Date                         datetime64[ns]
Transportation Expense                int64
Distance to Work                      int64
Age                                   int64
Daily Work Load Average             float64
Body Mass Index                       int64
Education                             int64
Children                              int64
Pets                                  int64
Absenteeism Time in Hours             int64
Reason_1                              int64
Reason_2                              int64
Reason_3                              int64
Reason_4                              int64
None                                  int64
dtype: object

In [13]:
raw_csv_data['Month']=raw_csv_data['Date'].dt.month
raw_csv_data['DayOfWeek']=raw_csv_data['Date'].dt.dayofweek

In [14]:
raw_csv_data.dtypes

Reason for Absence                    int64
Date                         datetime64[ns]
Transportation Expense                int64
Distance to Work                      int64
Age                                   int64
Daily Work Load Average             float64
Body Mass Index                       int64
Education                             int64
Children                              int64
Pets                                  int64
Absenteeism Time in Hours             int64
Reason_1                              int64
Reason_2                              int64
Reason_3                              int64
Reason_4                              int64
None                                  int64
Month                                 int32
DayOfWeek                             int32
dtype: object

In [15]:
raw_csv_data.info

<bound method DataFrame.info of      Reason for Absence       Date  Transportation Expense  Distance to Work  \
0                    26 2015-07-07                     289                36
1                     0 2015-07-14                     118                13
2                    23 2015-07-15                     179                51
3                     7 2015-07-16                     279                 5
4                    23 2015-07-23                     289                36
..                  ...        ...                     ...               ...
695                  10 2018-05-23                     179                22
696                   6 2018-05-23                     225                26
697                  10 2018-05-24                     330                16
698                  23 2018-05-24                     235                16
699                  28 2018-05-31                     291                31

     Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0     33                  239.554               30          1         2     1
1     50                  239.554               31          1         1     0
2     38                  239.554               31          1         0     0
3     39                  239.554               24          1         2     0
4     33                  239.554               30          1         2     1
..   ...                      ...              ...        ...       ...   ...
695   40                  237.656               22          2         2     0
696   28                  237.656               24          1         1     2
697   28                  237.656               25          2         0     0
698   32                  237.656               25          3         0     0
699   40                  237.656               25          1         1     1

     Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  None  \
0                            4         0         0         0         1     0
1                            0         0         0         0         0     1
2                            2         0         0         0         1     0
3                            4         1         0         0         0     0
4                            2         0         0         0         1     0
..                         ...       ...       ...       ...       ...   ...
695                          8         1         0         0         0     0
696                          3         1         0         0         0     0
697                          8         1         0         0         0     0
698                          2         0         0         0         1     0
699                          2         0         0         0         1     0

     Month  DayOfWeek
0        7          1
1        7          1
2        7          2
3        7          3
4        7          3
..     ...        ...
695      5          2
696      5          2
697      5          3
698      5          3
699      5          3

[700 rows x 18 columns]>

In [16]:
raw_csv_data['EducationLevel'] = raw_csv_data['Education'].isin(range(2,5)).map({True:1,False:0})

In [17]:
raw_csv_data.info

<bound method DataFrame.info of      Reason for Absence       Date  Transportation Expense  Distance to Work  \
0                    26 2015-07-07                     289                36
1                     0 2015-07-14                     118                13
2                    23 2015-07-15                     179                51
3                     7 2015-07-16                     279                 5
4                    23 2015-07-23                     289                36
..                  ...        ...                     ...               ...
695                  10 2018-05-23                     179                22
696                   6 2018-05-23                     225                26
697                  10 2018-05-24                     330                16
698                  23 2018-05-24                     235                16
699                  28 2018-05-31                     291                31

     Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0     33                  239.554               30          1         2     1
1     50                  239.554               31          1         1     0
2     38                  239.554               31          1         0     0
3     39                  239.554               24          1         2     0
4     33                  239.554               30          1         2     1
..   ...                      ...              ...        ...       ...   ...
695   40                  237.656               22          2         2     0
696   28                  237.656               24          1         1     2
697   28                  237.656               25          2         0     0
698   32                  237.656               25          3         0     0
699   40                  237.656               25          1         1     1

     Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  None  \
0                            4         0         0         0         1     0
1                            0         0         0         0         0     1
2                            2         0         0         0         1     0
3                            4         1         0         0         0     0
4                            2         0         0         0         1     0
..                         ...       ...       ...       ...       ...   ...
695                          8         1         0         0         0     0
696                          3         1         0         0         0     0
697                          8         1         0         0         0     0
698                          2         0         0         0         1     0
699                          2         0         0         0         1     0

     Month  DayOfWeek  EducationLevel
0        7          1               0
1        7          1               0
2        7          2               0
3        7          3               0
4        7          3               0
..     ...        ...             ...
695      5          2               1
696      5          2               0
697      5          3               1
698      5          3               1
699      5          3               0

[700 rows x 19 columns]>

In [18]:
raw_csv_data['EducationLevel'].unique()

array([0, 1])

In [19]:
raw_csv_data['EducationLevel'].value_counts()

EducationLevel
0    583
1    117
Name: count, dtype: int64

In [20]:
raw_csv_data.dtypes
raw_csv_data.describe()

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Reason_1,Reason_2,Reason_3,Reason_4,None,Month,DayOfWeek,EducationLevel
count,700.000000,700,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.00000,700.000000,700.000000
mean,19.411429,2016-12-31 00:45:15.428571392,222.347143,29.892857,36.417143,271.801774,26.737143,1.282857,1.021429,0.687143,6.761429,0.250000,0.008571,0.090000,0.597143,0.054286,6.36000,2.011429,0.167143
min,0.000000,2015-07-06 00:00:00,118.000000,5.000000,27.000000,205.917000,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000
25%,13.000000,2016-03-27 06:00:00,179.000000,16.000000,31.000000,241.476000,24.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.00000,1.000000,0.000000
50%,23.000000,2016-12-19 00:00:00,225.000000,26.000000,37.000000,264.249000,25.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,1.000000,0.000000,6.00000,2.000000,0.000000
75%,27.000000,2017-10-26 06:00:00,260.000000,50.000000,40.000000,294.217000,31.000000,1.000000,2.000000,1.000000,8.000000,0.250000,0.000000,0.000000,1.000000,0.000000,10.00000,3.000000,0.000000
max,28.000000,2018-05-31 00:00:00,388.000000,52.000000,58.000000,378.884000,38.000000,4.000000,4.000000,8.000000,120.000000,1.000000,1.000000,1.000000,1.000000,1.000000,12.00000,6.000000,1.000000
std,8.356292,NaN,66.312960,14.804446,6.379083,40.021804,4.254701,0.668090,1.112215,1.166095,12.670082,0.433322,0.092250,0.286386,0.490823,0.226743,3.50501,1.480396,0.373370

In [21]:
absenteeism_preprocessed = raw_csv_data[['Reason_1','Reason_2','Reason_3','Reason_4','None','Month','DayOfWeek','Transportation Expense',
                                         'Distance to Work','Age','Daily Work Load Average','Body Mass Index',
                                         'EducationLevel','Children','Pets','Absenteeism Time in Hours']].rename(columns={'EducationLevel':'Education'})
absenteeism_preprocessed.describe()

,Reason_1,Reason_2,Reason_3,Reason_4,None,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
count,700.000000,700.000000,700.000000,700.000000,700.000000,700.00000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
mean,0.250000,0.008571,0.090000,0.597143,0.054286,6.36000,2.011429,222.347143,29.892857,36.417143,271.801774,26.737143,0.167143,1.021429,0.687143,6.761429
std,0.433322,0.092250,0.286386,0.490823,0.226743,3.50501,1.480396,66.312960,14.804446,6.379083,40.021804,4.254701,0.373370,1.112215,1.166095,12.670082
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,118.000000,5.000000,27.000000,205.917000,19.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,3.00000,1.000000,179.000000,16.000000,31.000000,241.476000,24.000000,0.000000,0.000000,0.000000,2.000000
50%,0.000000,0.000000,0.000000,1.000000,0.000000,6.00000,2.000000,225.000000,26.000000,37.000000,264.249000,25.000000,0.000000,1.000000,0.000000,3.000000
75%,0.250000,0.000000,0.000000,1.000000,0.000000,10.00000,3.000000,260.000000,50.000000,40.000000,294.217000,31.000000,0.000000,2.000000,1.000000,8.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,12.00000,6.000000,388.000000,52.000000,58.000000,378.884000,38.000000,1.000000,4.000000,8.000000,120.000000

In [22]:
absenteeism_preprocessed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Reason_1                   700 non-null    int64
 1   Reason_2                   700 non-null    int64
 2   Reason_3                   700 non-null    int64
 3   Reason_4                   700 non-null    int64
 4   None                       700 non-null    int64
 5   Month                      700 non-null    int32
 6   DayOfWeek                  700 non-null    int32
 7   Transportation Expense     700 non-null    int64
 8   Distance to Work           700 non-null    int64
 9   Age                        700 non-null    int64
 10  Daily Work Load Average    700 non-null    float64
 11  Body Mass Index            700 non-null    int64
 12  Education                  700 non-null    int64
 13  Children                   700 non-null    int64
 14  Pets                       700 non-null    int64
 15  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int32(2), int64(13)
memory usage: 82.2 KB

In [23]:
absenteeism_preprocessed = absenteeism_preprocessed.drop(['None'], axis=1)

In [24]:
absenteeism_preprocessed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Reason_1                   700 non-null    int64
 1   Reason_2                   700 non-null    int64
 2   Reason_3                   700 non-null    int64
 3   Reason_4                   700 non-null    int64
 4   Month                      700 non-null    int32
 5   DayOfWeek                  700 non-null    int32
 6   Transportation Expense     700 non-null    int64
 7   Distance to Work           700 non-null    int64
 8   Age                        700 non-null    int64
 9   Daily Work Load Average    700 non-null    float64
 10  Body Mass Index            700 non-null    int64
 11  Education                  700 non-null    int64
 12  Children                   700 non-null    int64
 13  Pets                       700 non-null    int64
 14  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int32(2), int64(12)
memory usage: 76.7 KB

In [25]:
absenteeism_preprocessed.to_csv('../../../../statistics/python/Absenteeism/Absenteeism_preprocessed.csv', index=False)