In [91]:
import pandas as pd
my_original_data = pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_preprocessed.csv')
my_regenerated_data = pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_preprocessed_second.csv')
lectured_data = pd.read_csv('Absenteeism_preprocessed_lecture.csv')

In [92]:
my_original_data.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

In [93]:
my_regenerated_data.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

In [94]:
lectured_data.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

Now compare all of them.
First, my two data sets should be equal between them.
Then, my second data set should be equal to that of the lecture.

In [95]:
pd.unique(my_original_data.columns.values == my_regenerated_data.columns.values)

array([ True])

In [96]:
lectured_data.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet', 'Absenteeism Time in Hours'], dtype=object)

In [97]:
lectured_data.columns = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'DayOfWeek', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [98]:
pd.unique(my_original_data.columns.values == lectured_data.columns.values)

array([ True])

Desde este punto, todas las tablas tienen las mismas cabeceras de columna.

In [99]:
my_original_data.shape==my_regenerated_data.shape

True

In [100]:
my_original_data.shape==lectured_data.shape

True

Desde este punto, todas las tablas tienen las mismas dimensiones.

In [101]:
compare_mine=my_original_data == my_regenerated_data
compare_mine

,Reason_1,Reason_2,Reason_3,Reason_4,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
696,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
697,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
698,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
699,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [102]:
compare_mine.sum(axis=0)

Reason_1                     700
Reason_2                     700
Reason_3                     700
Reason_4                     700
Month                        700
DayOfWeek                    700
Transportation Expense       700
Distance to Work             700
Age                          700
Daily Work Load Average      700
Body Mass Index              700
Education                    700
Children                     700
Pets                         700
Absenteeism Time in Hours    700
dtype: int64

my_original_data y my_regenerated_data son iguales valor a valor.

In [103]:
compare_other = my_original_data==lectured_data

In [104]:
compare_other.sum(axis=0)

Reason_1                     700
Reason_2                     700
Reason_3                     700
Reason_4                     700
Month                        455
DayOfWeek                    483
Transportation Expense       700
Distance to Work             700
Age                          700
Daily Work Load Average      700
Body Mass Index              700
Education                    700
Children                     700
Pets                         700
Absenteeism Time in Hours    700
dtype: int64

Los campos de fechas han salido diferentes.
Vamos a mostrar las diferencias

In [115]:
month_different = my_original_data[compare_other['Month']==False]
day_different = my_original_data[compare_other['DayOfWeek']==False]

In [116]:
data_raw= pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_data.csv', sep=',', header=0,
                           parse_dates=['Date'], date_format="%d/%m/%Y")

In [124]:
raw_month_different = data_raw[compare_other['Month']==False]
raw_day_different = data_raw[compare_other['DayOfWeek']==False]

In [125]:
my_mega_day = pd.concat([day_different, raw_day_different],axis=1)
my_mega_day[['Date','Month','DayOfWeek']]

          Date  Month  DayOfWeek
5   2015-07-10      7          4
8   2015-07-06      7          0
19  2015-08-05      8          2
20  2015-08-12      8          2
21  2015-08-03      8          0
..         ...    ...        ...
680 2018-05-10      5          3
681 2018-05-10      5          3
682 2018-05-11      5          4
683 2018-05-11      5          4
684 2018-05-11      5          4

[217 rows x 3 columns]

In [120]:
my_mega = pd.concat([month_different, raw_month_different],axis=1)
my_mega[['Date','Month','DayOfWeek']]

          Date  Month  DayOfWeek
5   2015-07-10      7          4
8   2015-07-06      7          0
19  2015-08-05      8          2
20  2015-08-12      8          2
21  2015-08-03      8          0
..         ...    ...        ...
680 2018-05-10      5          3
681 2018-05-10      5          3
682 2018-05-11      5          4
683 2018-05-11      5          4
684 2018-05-11      5          4

[245 rows x 3 columns]

In [121]:
month_different_lecture = lectured_data[compare_other['Month']==False]
day_different_lecture = lectured_data[compare_other['DayOfWeek']==False]

In [122]:
their_mega = pd.concat([month_different_lecture, raw_month_different],axis=1)

In [126]:
their_mega_day = pd.concat([day_different_lecture,raw_day_different],axis=1)

In [127]:
their_mega_day[['Date','Month','DayOfWeek']]

          Date  Month  DayOfWeek
5   2015-07-10     10          2
8   2015-07-06      6          6
19  2015-08-05      5          4
20  2015-08-12     12          1
21  2015-08-03      3          6
..         ...    ...        ...
680 2018-05-10     10          4
681 2018-05-10     10          4
682 2018-05-11     11          0
683 2018-05-11     11          0
684 2018-05-11     11          0

[217 rows x 3 columns]

In [123]:
their_mega[['Date','Month','DayOfWeek']]

          Date  Month  DayOfWeek
5   2015-07-10     10          2
8   2015-07-06      6          6
19  2015-08-05      5          4
20  2015-08-12     12          1
21  2015-08-03      3          6
..         ...    ...        ...
680 2018-05-10     10          4
681 2018-05-10     10          4
682 2018-05-11     11          0
683 2018-05-11     11          0
684 2018-05-11     11          0

[245 rows x 3 columns]

## Here is the bug
It is clear now that the lecture data is the wrong one: they interpret some of the 'Date' data as 'YYYY-dd-MM' (those that differ) while others as 'YYYY-MM-dd', as I did. Here is a sample of the rows that differ:

```
        Date 	Month 	DayOfWeek
```
---

```
5 	2015-07-10 	10 	2
8 	2015-07-06 	6 	6
19 	2015-08-05 	5 	4
20 	2015-08-12 	12 	1
21 	2015-08-03 	3 	6
``` 

It is evident that at index 5 with date 2015-07-10, the month shall be 7 and not 10.

### Day of the week
The same way, in the column DayOfWeek the lecture data interprets day as the second field in the date, only wen the third is 12 or lower to be a month. The trick in this case is that some of this missinterpreted dates happen to fall in the same day of the week as the correct one. But as an example, in the display of `their_mega_day[['Date','Month','DayOfWeek']]` below:

```
        Date 	Month 	DayOfWeek
```
---

```
5 	2015-07-10 	10 	2
8 	2015-07-06 	6 	6
19 	2015-08-05 	5 	4
20 	2015-08-12 	12 	1
21 	2015-08-03 	3 	6
``` 

The 2015-07-10 is interpreted as October 7th being a Wednesday ('2' with Monday being '0') instead of July 10th which is a Friday ('4')

In [17]:
# Load data exactly as it is done in the preprocessing notebook
data_raw_orig = pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_data.csv', sep=',', header=0, index_col='ID',
                          dtype = {'ID': int,'Reason for Absence':int,'Transportation Expense':int,
                                    'Distance to Work':int,'Age':int,'Daily Work Load Average':float,'Body Mass Index':int,
                                    'Education':int,'Children':int,'Pets':int,'Absenteeism Time in Hours':int},
                           parse_dates=['Date'], date_format="%d/%m/%Y", decimal='.'
)
my_data_fields_orig = pd.DataFrame.copy(data_raw_orig[['Date']])
my_data_fields_orig  #ID column results different

         Date
ID
11 2015-07-07
36 2015-07-14
3  2015-07-15
7  2015-07-16
11 2015-07-23
..        ...
17 2018-05-23
28 2018-05-23
18 2018-05-24
25 2018-05-24
15 2018-05-31

[700 rows x 1 columns]

In [18]:
my_data_fields = pd.DataFrame.copy(data_raw[['Date']])
my_data_fields

          Date
0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
..         ...
695 2018-05-23
696 2018-05-23
697 2018-05-24
698 2018-05-24
699 2018-05-31

[700 rows x 1 columns]

In [19]:
type(my_data_fields['Date'])

pandas.core.series.Series

In [20]:
type(my_data_fields_orig['Date'])

pandas.core.series.Series

In [21]:
# using astype('int64') because having these as int32 was one of the differences in the Date fields
# my_data_fields['Month']=(my_data_fields['Date'].dt.month).astype('int64')
# my_data_fields['DayOfWeek']=(my_data_fields['Date'].dt.dayofweek).astype('int64')
# But returning to have them as it was at the beginning --int32-- does not cause the difference in results.
my_data_fields['Month']=(my_data_fields['Date'].dt.month)
my_data_fields['DayOfWeek']=(my_data_fields['Date'].dt.dayofweek)

In [22]:
my_data_fields_orig['Month']=(my_data_fields_orig['Date'].dt.month)
my_data_fields_orig['DayOfWeek']=(my_data_fields_orig['Date'].dt.dayofweek)

In [23]:
my_data_fields.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       700 non-null    datetime64[ns]
 1   Month      700 non-null    int32
 2   DayOfWeek  700 non-null    int32
dtypes: datetime64[ns](1), int32(2)
memory usage: 11.1 KB

In [24]:
my_data_fields_orig.info()  #Index remains different

<class 'pandas.core.frame.DataFrame'>
Index: 700 entries, 11 to 15
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       700 non-null    datetime64[ns]
 1   Month      700 non-null    int32
 2   DayOfWeek  700 non-null    int32
dtypes: datetime64[ns](1), int32(2)
memory usage: 16.4 KB

In [25]:
my_data_fields

          Date  Month  DayOfWeek
0   2015-07-07      7          1
1   2015-07-14      7          1
2   2015-07-15      7          2
3   2015-07-16      7          3
4   2015-07-23      7          3
..         ...    ...        ...
695 2018-05-23      5          2
696 2018-05-23      5          2
697 2018-05-24      5          3
698 2018-05-24      5          3
699 2018-05-31      5          3

[700 rows x 3 columns]

In [26]:
my_data_fields_orig  #the ID is different

         Date  Month  DayOfWeek
ID
11 2015-07-07      7          1
36 2015-07-14      7          1
3  2015-07-15      7          2
7  2015-07-16      7          3
11 2015-07-23      7          3
..        ...    ...        ...
17 2018-05-23      5          2
28 2018-05-23      5          2
18 2018-05-24      5          3
25 2018-05-24      5          3
15 2018-05-31      5          3

[700 rows x 3 columns]

In [27]:
my_data_fields_orig.iloc[1,:],my_data_fields_orig.iloc[1,0]

(Date         2015-07-14 00:00:00
 Month                          7
 DayOfWeek                      1
 Name: 36, dtype: object,
 Timestamp('2015-07-14 00:00:00'))

In [28]:
my_data_fields_orig['Date'].iloc[1],my_data_fields_orig['Date'].iloc[1].month,my_data_fields_orig['Date'].iloc[1].dayofweek

(Timestamp('2015-07-14 00:00:00'), 7, 1)

In [29]:
my_data_fields_orig['Date'].iloc[2],my_data_fields_orig['Date'].iloc[2].month,my_data_fields_orig['Date'].iloc[2].dayofweek

(Timestamp('2015-07-15 00:00:00'), 7, 2)

In [30]:
my_data_fields_orig['Date'].iloc[36],my_data_fields_orig['Date'].iloc[36].month,my_data_fields_orig['Date'].iloc[36].dayofweek

(Timestamp('2015-08-04 00:00:00'), 8, 1)

In [31]:
my_data_fields_orig['Date'].iloc[3],my_data_fields_orig['Date'].iloc[3].month,my_data_fields_orig['Date'].iloc[3].dayofweek

(Timestamp('2015-07-16 00:00:00'), 7, 3)

In [63]:
my_data_fields_orig.index

Index([11, 36,  3,  7, 11,  3, 10, 20, 14,  1,
       ...
       23, 17, 14, 25, 15, 17, 28, 18, 25, 15],
      dtype='int64', name='ID', length=700)

In [65]:
my_data_fields_orig.index = range(0,700)

In [66]:
my_data_fields_orig.index

RangeIndex(start=0, stop=700, step=1)

In [32]:
lectured_data_raw = pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_data.csv')
lectured_data_fields = pd.DataFrame.copy(lectured_data_raw[['Date']])
lectured_data_fields['Date'] = pd.to_datetime(lectured_data_fields['Date'], format = '%d/%m/%Y')
lectured_data_fields

          Date
0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
..         ...
695 2018-05-23
696 2018-05-23
697 2018-05-24
698 2018-05-24
699 2018-05-31

[700 rows x 1 columns]

In [33]:
type(lectured_data_fields['Date'])

pandas.core.series.Series

In [34]:
list_months = []
for i in range(lectured_data_fields.shape[0]):
    list_months.append(lectured_data_fields['Date'][i].month)

In [49]:
list_months[:10]

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

In [36]:
len(list_months)
lectured_data_fields['Month'] = list_months

In [37]:
def date_to_weekday(date_value):
    return date_value.weekday()

lectured_data_fields['DayOfWeek'] = lectured_data_fields['Date'].apply(date_to_weekday)

In [38]:
lectured_data_fields.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       700 non-null    datetime64[ns]
 1   Month      700 non-null    int64
 2   DayOfWeek  700 non-null    int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 16.5 KB

In [39]:
lectured_data_fields.columns.values

array(['Date', 'Month', 'DayOfWeek'], dtype=object)

In [40]:
my_data_fields.columns.values

array(['Date', 'Month', 'DayOfWeek'], dtype=object)

In [41]:
my_data_fields.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       700 non-null    datetime64[ns]
 1   Month      700 non-null    int32
 2   DayOfWeek  700 non-null    int32
dtypes: datetime64[ns](1), int32(2)
memory usage: 11.1 KB

In [70]:
comparison = my_data_fields == lectured_data_fields
comparison.sum(axis=0)

Date         700
Month        700
DayOfWeek    700
dtype: int64

In [43]:
pd.unique(comparison['Date'])

array([ True])

Something was different from the preprocessing:
The way to obtain Date fields made them different.

In [69]:
compare_fields_other = my_data_fields_orig == lectured_data_fields
compare_fields_other.sum(axis=0)

Date         700
Month        700
DayOfWeek    700
dtype: int64

# Solution
Seems to be the Index column. Let's start over and drop the index column when loading preprocessed data

In [71]:
my_original_data = pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_preprocessed.csv')
my_regenerated_data = pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_preprocessed_second.csv')
lectured_data = pd.read_csv('Absenteeism_preprocessed_lecture.csv')

## Final diagnostic
The Month column in the lecture data has been taken as if the dates were 'YYYY-dd-MM' where possible (i.e. when day < 12)

The difference being originated because I imported the raw data indicating that the "Date" column was to be interpreted as a 'YYYY-MM-dd' date, which is correct.